# Change these first
owner: integrated-wellness-inc # Your GitHub organization or username, where this repository lives
repo: status.golivwell # The name of this repository
user-agent: integrated-wellness-inc

sites:
  - name: admin dashboard site
    url: https://app.golivwell.com
  - name: marketing site
    url: https://golivwell.com
  - name: livwell api
    url: https://api.golivwell.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.golivwell.com
  # baseUrl: /status.golivwell
  logoUrl: https://github.com/integrated-wellness-inc.png
  name: Golivwell Status Monitor
  introTitle: "**Livwell** is the **All-in-one** wellness solution for wellness businesses"
  introMessage: This is the status.golivwell.com site, where you can see the status of all the Livwell websites, and outages are automatically reported. Uses [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  commitMessages:
    commitAuthorName: "ogdev-01"
    commitAuthorEmail: "62995161+ogdev-01@users.noreply.github.com"
assignees:
  - ogdev-01
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
